"""Structured logging configuration (AWS Lambda Powertools).

Provides a single factory, :func:`get_logger`, that returns a Powertools
``Logger`` pre-configured to emit structured JSON to CloudWatch Logs. Powertools
already serializes every log record as JSON and injects standard keys
(``timestamp``, ``level``, ``service``, ``function_name``, ``cold_start``,
``xray_trace_id``). Handlers should additionally call
``logger.append_keys(correlation_id=...)`` so the UUID v4 generated by the
Webhook_Receiver is propagated through every downstream log line (Requirement
13.1 / 13.2).

Usage::

    from shared.logger import get_logger

    logger = get_logger("message-processor")

    @logger.inject_lambda_context
    def handler(event, context):
        logger.append_keys(correlation_id=event["correlationId"])
        logger.info("processing message")
"""

from __future__ import annotations

from aws_lambda_powertools import Logger

# Default service name used when a component does not pass an explicit one.
DEFAULT_SERVICE_NAME: str = "btg-connectai"


def get_logger(service: str = DEFAULT_SERVICE_NAME, **kwargs: object) -> Logger:
    """Return a Powertools ``Logger`` emitting structured JSON.

    Args:
        service: Logical service name attached to every log record (e.g.
            ``"message-processor"``, ``"auth-service"``). Defaults to
            :data:`DEFAULT_SERVICE_NAME`.
        **kwargs: Additional keyword arguments forwarded to
            ``aws_lambda_powertools.Logger`` (for example ``level`` or
            ``sampling_rate``).

    Returns:
        A configured :class:`aws_lambda_powertools.Logger` instance.
    """
    return Logger(service=service, **kwargs)


__all__ = ["get_logger", "DEFAULT_SERVICE_NAME"]
