"""SQS enqueue logic for the Webhook_Receiver Lambda.

Publishes a parsed Twilio webhook payload to the inbound SQS FIFO queue created
by the ``infra`` repo (URL resolved from the cross-stack contract and injected
via the ``INBOUND_QUEUE_URL`` environment variable).

The queue is FIFO so two attributes are mandatory on every message:

* ``MessageGroupId = From`` — the client's WhatsApp phone number. Guarantees
  ordered delivery per client without serializing distinct clients.
* ``MessageDeduplicationId = MessageSid`` — Twilio's unique message id. Provides
  native deduplication over the FIFO 5-minute window, absorbing Twilio webhook
  retries without a custom dedup table (Requirement 3.4).

The message body is JSON: every field of the original payload plus a
``correlationId`` (UUID v4 generated by the handler) and a ``receivedAt`` ISO
8601 UTC timestamp, so downstream Lambdas can trace and order the interaction
(Requirement 3.3).
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any

import boto3

from shared.logger import get_logger

logger = get_logger("webhook-receiver")

# Module-level client so the connection is reused across warm invocations.
_sqs = boto3.client("sqs")


def _get_queue_url() -> str:
    """Resolve the inbound FIFO queue URL from the environment.

    Read lazily (inside the function rather than at import time) so the module
    can be imported without the environment variable being set — tests inject
    ``INBOUND_QUEUE_URL`` before invoking :func:`enqueue_message`.

    Returns:
        The inbound SQS FIFO queue URL.

    Raises:
        KeyError: If ``INBOUND_QUEUE_URL`` is not configured.
    """
    return os.environ["INBOUND_QUEUE_URL"]


def enqueue_message(payload: dict[str, Any], correlation_id: str) -> dict[str, Any]:
    """Enqueue a parsed Twilio webhook payload on the inbound FIFO queue.

    Builds the message body by spreading the original payload fields and adding
    ``correlationId`` and ``receivedAt`` (ISO 8601 UTC). Sends it to the queue
    using ``From`` as the FIFO group id and ``MessageSid`` as the deduplication
    id.

    Args:
        payload: The parsed Twilio webhook fields. Must contain ``From`` and
            ``MessageSid``.
        correlation_id: UUID v4 generated by the handler for end-to-end tracing.

    Returns:
        The raw ``sqs.send_message`` response (includes ``MessageId`` and, for
        FIFO queues, ``SequenceNumber``).

    Raises:
        KeyError: If ``payload`` is missing ``From`` or ``MessageSid``, or if
            ``INBOUND_QUEUE_URL`` is not set.
    """
    queue_url = _get_queue_url()

    body = {
        **payload,
        "correlationId": correlation_id,
        "receivedAt": datetime.now(timezone.utc).isoformat(),
    }

    response = _sqs.send_message(
        QueueUrl=queue_url,
        MessageBody=json.dumps(body),
        MessageGroupId=payload["From"],  # Ordering per client
        MessageDeduplicationId=payload["MessageSid"],  # Native 5-min dedup
    )

    logger.info(
        "message enqueued",
        extra={
            "correlation_id": correlation_id,
            "message_id": response.get("MessageId"),
            "message_sid": payload["MessageSid"],
        },
    )
    return response


__all__ = ["enqueue_message"]
