"""Auth_Service Lambda — mock login endpoint behind a Function URL.

This Lambda backs the Login_Page (S3 static site). The browser, having received
a WhatsApp login link of the form
``{LOGIN_PAGE_URL}?phone=<phone>&token=<callback-token>``, presents a login form
and then ``POST``s the credentials here. The Lambda is exposed through a Lambda
**Function URL** (not API Gateway), so it must handle CORS preflight itself.

Endpoint
--------
``POST /authenticate`` — request body (JSON)::

    {
      "username": "carlos.rodriguez",
      "password": "BtgDemo2025!",
      "phone":    "+573001112233",
      "token":    "<expEpoch>.<hmacSHA256>"
    }

Responses (JSON, always with CORS headers):

* ``200 {"status": "success"}`` — credentials valid, phone matches, token valid;
  an Auth_Session was written (Req 5.3).
* ``401 {"status": "error", "error": "invalid_credentials"}`` — unknown
  username, wrong password, or the user's phone does not match the link's phone
  (Req 5.5 / 5.7).
* ``403 {"status": "error", "error": "invalid_token"}`` — the callback token is
  missing, malformed, expired or has a bad signature.
* ``400 {"status": "error", "error": "bad_request"}`` — body missing/not JSON or
  required fields absent.
* ``200`` (empty) for ``OPTIONS`` preflight.

Validation pipeline (Req 5.3 / 5.5 / 5.7 / 6.1)
-----------------------------------------------
1. Validate the signed callback token against the submitted phone
   (:func:`is_valid_callback_token`). Reject forged/expired links → 403.
2. Look up the user by ``username`` + ``password`` (:func:`users.find_user`).
   No match → 401.
3. Verify the found user's ``phone_number`` matches the link's phone. A user may
   only authenticate the phone the link was issued for → 401 on mismatch.
4. Write an Auth_Session item (30-minute TTL,
   :data:`shared.constants.AUTH_SESSION_TTL`) keyed by the normalized E.164
   phone number, then return success.

Shared-secret dependency (IMPORTANT)
------------------------------------
The callback token is generated by the **Message_Processor**
(``message_processor.auth.generate_callback_token``) and validated here. Both
Lambdas MUST be configured with the **same** ``CALLBACK_TOKEN_SECRET`` value at
runtime (injected from Secrets Manager / SSM by ``infra``). If the secrets
diverge, every login link will be rejected as an invalid signature. The signing
scheme is intentionally duplicated (not imported) because the two Lambdas are
packaged independently and must not depend on each other's code.

Session id
----------
The Message_Processor derives a *conversational* session id deterministically
from the phone number (for Bedrock Agent memory). The Auth_Session ``sessionId``
written here is an independent random UUID v4 identifying the login session —
the two are deliberately decoupled, so this Lambda does not import the
Message_Processor's derivation logic.

Cross-stack / environment contract
----------------------------------
* ``AUTH_TABLE_NAME`` — Auth_Session DynamoDB table name (from the ``infra``
  contract). Read lazily so the module imports without the env configured.
* ``CALLBACK_TOKEN_SECRET`` — HMAC signing key shared with the Message_Processor.
* ``LOGIN_PAGE_ORIGIN`` — allowed CORS origin for the Login_Page. Defaults to
  ``"*"`` for the MVP demo (documented relaxation; tighten to the real S3 /
  CloudFront origin in production).
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

import boto3

from shared.constants import AUTH_SESSION_TTL
from shared.logger import get_logger
from shared.masking import mask_phone
from shared.twilio_env import hydrate_twilio_env

from .login_page import LOGIN_PAGE_HTML
from .users import find_user

logger = get_logger("auth-service")

# Module-level boto3 resource reused across warm invocations.
_dynamodb = boto3.resource("dynamodb")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _normalize_phone(phone_number: str) -> str:
    """Normalize a phone number to a bare E.164 string.

    Mirrors ``message_processor.auth._normalize_phone`` so the token signature
    (computed over the normalized phone) verifies and the Auth_Session partition
    key matches what the Message_Processor reads. Strips an optional
    ``whatsapp:`` channel prefix and surrounding whitespace.

    Args:
        phone_number: A raw phone identifier, optionally ``whatsapp:``-prefixed.

    Returns:
        The trimmed E.164 phone number without the channel prefix.
    """
    return phone_number.strip().removeprefix("whatsapp:").strip()


def _get_auth_table():
    """Return the Auth_Session DynamoDB table resource (name read lazily)."""
    return _dynamodb.Table(os.environ["AUTH_TABLE_NAME"])


def _now() -> datetime:
    """Return the current UTC time (isolated for testability)."""
    return datetime.now(timezone.utc)


def _cors_headers() -> dict[str, str]:
    """Return the CORS headers for the Login_Page origin.

    The allowed origin comes from ``LOGIN_PAGE_ORIGIN`` and defaults to ``"*"``
    for the MVP demo (documented relaxation — tighten to the real Login_Page
    origin in production).
    """
    return {
        "Access-Control-Allow-Origin": os.environ.get("LOGIN_PAGE_ORIGIN", "*"),
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
    }


def _response(status_code: int, body: dict[str, Any] | None) -> dict[str, Any]:
    """Build a Function URL response with JSON body and CORS headers."""
    headers = {"Content-Type": "application/json", **_cors_headers()}
    return {
        "statusCode": status_code,
        "headers": headers,
        "body": json.dumps(body) if body is not None else "",
    }


def _parse_body(event: dict[str, Any]) -> dict[str, Any] | None:
    """Parse the (optionally base64-encoded) JSON request body.

    Args:
        event: The Lambda Function URL event.

    Returns:
        The decoded JSON object as a dict, or ``None`` if the body is missing or
        not a valid JSON object.
    """
    raw_body = event.get("body")
    if not raw_body:
        return None

    if event.get("isBase64Encoded"):
        try:
            raw_body = base64.b64decode(raw_body).decode("utf-8")
        except (ValueError, UnicodeDecodeError):
            return None

    try:
        parsed = json.loads(raw_body)
    except (json.JSONDecodeError, TypeError):
        return None

    return parsed if isinstance(parsed, dict) else None


def _http_method(event: dict[str, Any]) -> str:
    """Extract the HTTP method from a Function URL (payload v2.0) event."""
    return (
        (event.get("requestContext") or {}).get("http", {}).get("method", "")
    ).upper()


# ---------------------------------------------------------------------------
# Callback token validation (shared scheme with Message_Processor)
# ---------------------------------------------------------------------------


def is_valid_callback_token(phone: str, token: str) -> bool:
    """Validate a signed, time-bound callback token for a phone number.

    Mirrors the generation scheme in
    ``message_processor.auth.generate_callback_token``: the token is
    ``"<expEpoch>.<signature>"`` where ``signature`` is an HMAC-SHA256 over
    ``"<normalized_phone>:<expEpoch>"`` keyed with ``CALLBACK_TOKEN_SECRET``.

    The token is valid only when **all** of the following hold:

    * it is well-formed (``"<int>.<hex>"``),
    * the embedded expiry is strictly in the future (``exp > now``), and
    * the re-derived HMAC matches the supplied signature (constant-time
      comparison via :func:`hmac.compare_digest`).

    Args:
        phone: The phone number the link was issued for (``whatsapp:`` prefix
            optional; normalized before signing).
        token: The callback token from the login link.

    Returns:
        ``True`` if the token is authentic and unexpired, ``False`` otherwise.
        Returns ``False`` (never raises) for any malformed input.
    """
    if not token:
        return False

    secret = os.environ.get("CALLBACK_TOKEN_SECRET")
    if not secret:
        # Fail closed: without the shared secret we cannot trust any token.
        logger.error("CALLBACK_TOKEN_SECRET not set; rejecting all tokens")
        return False

    exp_str, sep, signature = token.partition(".")
    if not sep or not exp_str or not signature:
        return False

    try:
        exp_epoch = int(exp_str)
    except ValueError:
        return False

    # Reject expired tokens (exp <= now).
    if exp_epoch <= int(_now().timestamp()):
        return False

    normalized = _normalize_phone(phone)
    expected = hmac.new(
        secret.encode("utf-8"),
        f"{normalized}:{exp_epoch}".encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    return hmac.compare_digest(expected, signature)


# ---------------------------------------------------------------------------
# Auth_Session persistence (Req 5.3 / 6.1)
# ---------------------------------------------------------------------------


def _create_auth_session(phone: str, user: dict[str, Any]) -> dict[str, Any]:
    """Write an Auth_Session item for ``user`` keyed by ``phone`` (30-min TTL).

    Builds and persists an Auth_Session record (Req 5.3 / 6.1): partition key is
    the normalized E.164 phone number, with a TTL of
    :data:`shared.constants.AUTH_SESSION_TTL` (30 minutes) expressed both as a
    unix-epoch ``ttl`` (for DynamoDB TTL deletion) and an ISO 8601 ``expiresAt``.

    Args:
        phone: The normalized E.164 phone number (partition key).
        user: The matched demo user record.

    Returns:
        The Auth_Session item that was written (for logging/testing).
    """
    now = _now()
    expires_at = now + timedelta(seconds=AUTH_SESSION_TTL)

    item = {
        "pk": phone,
        "sessionId": str(uuid.uuid4()),
        "username": user["username"],
        "name": user["name"],
        "documentId": user["document_id"],
        "email": user["email"],
        "createdAt": now.isoformat(),
        "expiresAt": expires_at.isoformat(),
        "ttl": int(expires_at.timestamp()),
    }

    _get_auth_table().put_item(Item=item)
    return item


# ---------------------------------------------------------------------------
# Lambda handler
# ---------------------------------------------------------------------------


@logger.inject_lambda_context
def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Authenticate a Login_Page submission and create an Auth_Session.

    Handles ``OPTIONS`` (CORS preflight) and ``POST`` to ``/authenticate``. See
    the module docstring for the full request/response contract.

    Args:
        event: Lambda Function URL (payload format v2.0) event.
        context: Lambda context object (unused beyond Powertools injection).

    Returns:
        A Function URL response dict with a JSON body and CORS headers.
    """
    method = _http_method(event)

    # Hydrate CALLBACK_TOKEN_SECRET (and Twilio vars) from the Twilio secret so
    # token verification uses the same shared HMAC key as the Message_Processor.
    hydrate_twilio_env()

    # CORS preflight — browsers send this before the cross-origin POST.
    if method == "OPTIONS":
        return _response(200, None)

    # GET → serve the self-contained Login_Page (HTTPS via the Function URL).
    # The page reads phone/token from the query string and POSTs back here.
    if method == "GET":
        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "text/html; charset=utf-8",
                "Cache-Control": "no-store",
            },
            "body": LOGIN_PAGE_HTML,
        }

    if method != "POST":
        return _response(405, {"status": "error", "error": "method_not_allowed"})

    body = _parse_body(event)
    if body is None:
        return _response(400, {"status": "error", "error": "bad_request"})

    username = body.get("username")
    password = body.get("password")
    phone = body.get("phone")
    token = body.get("token")

    if not (username and password and phone and token):
        return _response(400, {"status": "error", "error": "bad_request"})

    normalized_phone = _normalize_phone(phone)

    # 1. Validate the signed callback token for this phone (Req 5.2 link
    #    integrity). Never log the token or full phone.
    if not is_valid_callback_token(phone, token):
        logger.warning(
            "invalid callback token", extra={"phone": mask_phone(normalized_phone)}
        )
        return _response(403, {"status": "error", "error": "invalid_token"})

    # 2. Check credentials (Req 5.5). Never log the password.
    user = find_user(username, password)
    if user is None:
        logger.warning(
            "invalid credentials",
            extra={"username": username, "phone": mask_phone(normalized_phone)},
        )
        return _response(401, {"status": "error", "error": "invalid_credentials"})

    # 3. The user may only authenticate the phone the login link was issued for
    #    (Req 5.7). Mismatch → reject.
    if _normalize_phone(user["phone_number"]) != normalized_phone:
        logger.warning(
            "phone mismatch for user",
            extra={"username": username, "phone": mask_phone(normalized_phone)},
        )
        return _response(401, {"status": "error", "error": "invalid_credentials"})

    # 4. Create the Auth_Session (30-min TTL) keyed by phone (Req 5.3 / 6.1).
    _create_auth_session(normalized_phone, user)
    logger.info(
        "auth session created",
        extra={"username": username, "phone": mask_phone(normalized_phone)},
    )

    return _response(200, {"status": "success"})


__all__ = ["handler", "is_valid_callback_token"]
